//! The locally efficient repeated-cross-section `DR-DiD` estimator.
//!
//! Sant'Anna and Zhao (2020), the estimator `DRDID::drdid_rc` implements and the
//! one `did::att_gt` calls for `est_method = "dr"` on repeated cross sections.
//!
//! # How it differs from [`super::repeated`]
//!
//! That module is the TRADITIONAL estimator, `DRDID::drdid_rc1`. It regresses the
//! outcome on covariates for the CONTROL group only, once per period, and
//! combines that with the propensity score.
//!
//! This one fits FOUR outcome regressions, treated and control in each period,
//! and adds the terms that make the estimator locally efficient: it attains the
//! semiparametric efficiency bound when both nuisance models are correctly
//! specified, rather than merely staying consistent when one of them is.
//!
//! The two agree on the point estimate far more often than they agree on the
//! standard error. Measured on `mpdta` cell (2004, 2004) they give the same ATT
//! to 1e-9 and standard errors of 0.0922804 and 0.0897358, a 2.8% gap. That is
//! why `tests/did_attgt_dr_ref.json` could never be made to pass against the
//! traditional route: it was generated by `did`, and `did` calls this one.
//!
//! # Notes on matching the reference exactly
//!
//! Three details in `DRDID::drdid_rc` are easy to miss and each moves the answer:
//!
//! * Sampling weights are normalised to mean one BEFORE anything else, so every
//!   `mean(...)` below is over the full sample rather than over a subgroup.
//! * Trimming is asymmetric. Treated rows are kept whatever their propensity
//!   score; control rows are dropped above `trim_level`. A symmetric rule
//!   discards treated observations the reference keeps.
//! * The residual inside each regression's asymptotic linear representation uses
//!   THAT regression's own fitted values, not the period-combined control
//!   prediction used in the `eta` terms.

use faer::Mat;

use crate::estimators::common::linalg::solve_spd_system_multi_rhs;
use crate::estimators::outcome::linear::LinearOutcome;
use crate::estimators::outcome::model::OutcomeModel;
use crate::estimators::propensity::common::logistic_scores;
use crate::estimators::propensity::logistic::LogisticPS;
use crate::estimators::propensity::types::{Config as PropensityConfig, PropensityEstimator};
use crate::inference::{multiplier_bootstrap_ci, standard_error_from_influence};
use crate::types::{DrDidConfig, DrDidError, DrDidEstimate, DrDidRepeatedObservation};
use crate::util::usize_to_f64;

/// `DRDID`'s control-group trimming threshold.
const CONTROL_TRIM_LEVEL: f64 = 0.995;

/// One weighted least-squares fit, plus what the influence function needs from it.
struct WeightedRegression {
    /// Fitted values for EVERY row, not only the subset that was fitted on.
    predictions: Vec<f64>,
    /// The asymptotic linear representation, `n x k` row-major:
    /// `w * (y - fitted) * X * inv(X' diag(w) X / n)`.
    asymptotic_linear: Vec<f64>,
}

/// Fit `y ~ X` by weighted least squares, where `weights` is already zero outside
/// the subgroup being fitted.
///
/// Carrying the subgroup in the weights rather than by slicing is what lets the
/// `n` in `X' diag(w) X / n` be the FULL sample size, which is what the reference
/// divides by and what makes the representations of different subgroups
/// commensurable when they are added together later.
fn weighted_regression(
    design: &Mat<f64>,
    outcome: &[f64],
    weights: &[f64],
    ridge: f64,
) -> Result<WeightedRegression, DrDidError> {
    let n = design.nrows();
    let k = design.ncols();
    let n_f = usize_to_f64(n);

    let subset = weights
        .iter()
        .enumerate()
        .filter(|(_, weight)| **weight > 0.0)
        .map(|(row, _)| row)
        .collect::<Vec<_>>();
    if subset.len() < k {
        return Err(DrDidError::InvalidConfig(format!(
            "a locally efficient outcome regression had {} rows for {k} parameters",
            subset.len()
        )));
    }

    let subset_design = Mat::from_fn(subset.len(), k, |row, col| *design.get(subset[row], col));
    let subset_outcome = Mat::from_fn(subset.len(), 1, |row, _| outcome[subset[row]]);
    let subset_weights = subset.iter().map(|row| weights[*row]).collect::<Vec<f64>>();

    let model = LinearOutcome { ridge };
    let coefficients = model.fit(
        subset_design.as_ref(),
        subset_outcome.as_ref(),
        Some(&subset_weights),
    );
    let predictions = model.predict(design.as_ref(), coefficients.as_ref());

    // X' diag(w) X / n, over the full sample because w is zero outside the subset.
    let mut gram = vec![0.0; k * k];
    for (row, &weight) in weights.iter().enumerate().take(n) {
        if weight == 0.0 {
            continue;
        }
        for i in 0..k {
            let xi = *design.get(row, i) * weight;
            for j in 0..k {
                gram[i * k + j] += xi * *design.get(row, j);
            }
        }
    }
    for value in &mut gram {
        *value /= n_f;
    }

    // asy_lin = B inv(G), obtained as (inv(G) B')' since G is symmetric.
    let mut scores = vec![0.0; n * k];
    for row in 0..n {
        let scale = weights[row] * (outcome[row] - predictions[row]);
        for col in 0..k {
            scores[row * k + col] = scale * *design.get(row, col);
        }
    }
    let rhs = Mat::from_fn(k, n, |i, j| scores[j * k + i]);
    let solved = solve_spd_system_multi_rhs(&gram, &rhs).map_err(|message| {
        DrDidError::InvalidConfig(format!(
            "locally efficient regression is singular: {message}"
        ))
    })?;
    let mut asymptotic_linear = vec![0.0; n * k];
    for row in 0..n {
        for col in 0..k {
            asymptotic_linear[row * k + col] = *solved.get(col, row);
        }
    }

    Ok(WeightedRegression {
        predictions,
        asymptotic_linear,
    })
}

/// `(v' X) / n`, the row vector each influence term is projected onto.
fn moment(design: &Mat<f64>, values: &[f64]) -> Vec<f64> {
    let k = design.ncols();
    let n_f = usize_to_f64(design.nrows());
    (0..k)
        .map(|col| {
            values
                .iter()
                .enumerate()
                .map(|(row, value)| value * *design.get(row, col))
                .sum::<f64>()
                / n_f
        })
        .collect()
}

/// `A m`, an `n x k` representation applied to a `k` vector.
fn project(representation: &[f64], m: &[f64], n: usize) -> Vec<f64> {
    let k = m.len();
    (0..n)
        .map(|row| {
            (0..k)
                .map(|col| representation[row * k + col] * m[col])
                .sum()
        })
        .collect()
}

fn mean(values: &[f64]) -> f64 {
    values.iter().sum::<f64>() / usize_to_f64(values.len())
}

/// Estimate the ATT by the locally efficient repeated-cross-section `DR-DiD`.
///
/// # Errors
/// Returns [`DrDidError`] when the configuration or inputs are invalid, a cell is
/// empty, or a nuisance regression cannot be fitted.
pub fn estimate_drdid_repeated_efficient(
    observations: &[DrDidRepeatedObservation],
    config: DrDidConfig,
) -> Result<DrDidEstimate, DrDidError> {
    super::repeated::validate_config(config)?;
    if observations.is_empty() {
        return Err(DrDidError::EmptyInput);
    }
    let prepared = super::repeated::prepare(observations)?;
    let n = prepared.treated_indicator.len();
    let k = prepared.feature_count;
    let n_f = usize_to_f64(n);

    let design = Mat::from_fn(n, k, |row, col| prepared.design_matrix_flat[row * k + col]);
    let weights = super::repeated::normalize_weights(&prepared.sampling_weights)?;
    let treated = &prepared.treated_indicator;
    let post = &prepared.post_indicator;
    let outcome = &prepared.outcome;

    // Propensity score, clipped as the reference clips it.
    let propensity_config = PropensityConfig {
        max_iter: u64::try_from(config.max_iter)
            .map_err(|_| DrDidError::InvalidConfig("max_iter exceeds u64".to_string()))?,
        tol: config.tol,
        min_weight: config.propensity_clip,
        vstar: 700.0,
    };
    let target = Mat::from_fn(n, 1, |row, _| treated[row]);
    let fitted_ps = LogisticPS::new(propensity_config)
        .fit(design.as_ref(), target.as_ref())
        .map_err(|err| DrDidError::InvalidConfig(err.to_string()))?;
    let propensity = logistic_scores(design.as_ref(), fitted_ps.beta.as_ref())
        .into_iter()
        .map(|score| score.clamp(config.propensity_clip, 1.0 - 1e-6))
        .collect::<Vec<f64>>();

    // Asymmetric trimming: treated rows are always kept.
    let trim = (0..n)
        .map(|row| {
            if treated[row] > 0.5 || propensity[row] < CONTROL_TRIM_LEVEL {
                1.0
            } else {
                0.0
            }
        })
        .collect::<Vec<f64>>();

    // Four outcome regressions.
    let indicator = |is_treated: bool, is_post: bool| -> Vec<f64> {
        (0..n)
            .map(|row| {
                let treated_match = (treated[row] > 0.5) == is_treated;
                let post_match = (post[row] > 0.5) == is_post;
                if treated_match && post_match {
                    weights[row]
                } else {
                    0.0
                }
            })
            .collect()
    };
    let control_pre_weights = indicator(false, false);
    let control_post_weights = indicator(false, true);
    let treated_pre_weights = indicator(true, false);
    let treated_post_weights = indicator(true, true);

    let control_pre = weighted_regression(&design, outcome, &control_pre_weights, config.ridge)?;
    let control_post = weighted_regression(&design, outcome, &control_post_weights, config.ridge)?;
    let treated_pre = weighted_regression(&design, outcome, &treated_pre_weights, config.ridge)?;
    let treated_post = weighted_regression(&design, outcome, &treated_post_weights, config.ridge)?;

    let control_prediction = (0..n)
        .map(|row| {
            if post[row] > 0.5 {
                control_post.predictions[row]
            } else {
                control_pre.predictions[row]
            }
        })
        .collect::<Vec<f64>>();

    // The eight weight vectors.
    let build = |f: &dyn Fn(usize) -> f64| (0..n).map(f).collect::<Vec<f64>>();
    let w_treat_pre = build(&|row| trim[row] * weights[row] * treated[row] * (1.0 - post[row]));
    let w_treat_post = build(&|row| trim[row] * weights[row] * treated[row] * post[row]);
    let w_cont_pre = build(&|row| {
        trim[row] * weights[row] * propensity[row] * (1.0 - treated[row]) * (1.0 - post[row])
            / (1.0 - propensity[row])
    });
    let w_cont_post = build(&|row| {
        trim[row] * weights[row] * propensity[row] * (1.0 - treated[row]) * post[row]
            / (1.0 - propensity[row])
    });
    let w_d = build(&|row| trim[row] * weights[row] * treated[row]);
    let w_dt1 = build(&|row| trim[row] * weights[row] * treated[row] * post[row]);
    let w_dt0 = build(&|row| trim[row] * weights[row] * treated[row] * (1.0 - post[row]));

    let (mw_treat_pre, mw_treat_post) = (mean(&w_treat_pre), mean(&w_treat_post));
    let (mw_cont_pre, mw_cont_post) = (mean(&w_cont_pre), mean(&w_cont_post));
    let (mw_d, mw_dt1, mw_dt0) = (mean(&w_d), mean(&w_dt1), mean(&w_dt0));
    for (label, value) in [
        ("treated pre", mw_treat_pre),
        ("treated post", mw_treat_post),
        ("control pre", mw_cont_pre),
        ("control post", mw_cont_post),
    ] {
        if value <= 0.0 {
            return Err(DrDidError::InvalidConfig(format!(
                "the {label} cell has no weight after trimming"
            )));
        }
    }

    let eta = |w: &[f64], value: &dyn Fn(usize) -> f64, mw: f64| -> Vec<f64> {
        (0..n).map(|row| w[row] * value(row) / mw).collect()
    };
    let residual = |row: usize| outcome[row] - control_prediction[row];
    let treated_gap_post =
        |row: usize| treated_post.predictions[row] - control_post.predictions[row];
    let treated_gap_pre = |row: usize| treated_pre.predictions[row] - control_pre.predictions[row];

    let eta_treat_pre = eta(&w_treat_pre, &residual, mw_treat_pre);
    let eta_treat_post = eta(&w_treat_post, &residual, mw_treat_post);
    let eta_cont_pre = eta(&w_cont_pre, &residual, mw_cont_pre);
    let eta_cont_post = eta(&w_cont_post, &residual, mw_cont_post);
    let eta_d_post = eta(&w_d, &treated_gap_post, mw_d);
    let eta_dt1_post = eta(&w_dt1, &treated_gap_post, mw_dt1);
    let eta_d_pre = eta(&w_d, &treated_gap_pre, mw_d);
    let eta_dt0_pre = eta(&w_dt0, &treated_gap_pre, mw_dt0);

    let att_treat_pre = mean(&eta_treat_pre);
    let att_treat_post = mean(&eta_treat_post);
    let att_cont_pre = mean(&eta_cont_pre);
    let att_cont_post = mean(&eta_cont_post);
    let att_d_post = mean(&eta_d_post);
    let att_dt1_post = mean(&eta_dt1_post);
    let att_d_pre = mean(&eta_d_pre);
    let att_dt0_pre = mean(&eta_dt0_pre);

    let att = (att_treat_post - att_treat_pre) - (att_cont_post - att_cont_pre)
        + (att_d_post - att_dt1_post)
        - (att_d_pre - att_dt0_pre);

    // The propensity score's asymptotic linear representation.
    let mut ps_gram = vec![0.0; k * k];
    for row in 0..n {
        let hessian_weight = propensity[row] * (1.0 - propensity[row]) * weights[row];
        for i in 0..k {
            let xi = *design.get(row, i) * hessian_weight;
            for j in 0..k {
                ps_gram[i * k + j] += xi * *design.get(row, j);
            }
        }
    }
    let ps_scores = (0..n)
        .flat_map(|row| {
            let scale = weights[row] * (treated[row] - propensity[row]);
            (0..k)
                .map(|col| scale * *design.get(row, col))
                .collect::<Vec<f64>>()
        })
        .collect::<Vec<f64>>();
    let ps_rhs = Mat::from_fn(k, n, |i, j| ps_scores[j * k + i]);
    let ps_solved = solve_spd_system_multi_rhs(&ps_gram, &ps_rhs)
        .map_err(|m| DrDidError::InvalidConfig(format!("propensity design is singular: {m}")))?;
    // Hessian carries a factor of n, so the representation does too.
    let ps_representation = (0..n)
        .flat_map(|row| {
            (0..k)
                .map(|col| *ps_solved.get(col, row) * n_f)
                .collect::<Vec<f64>>()
        })
        .collect::<Vec<f64>>();

    let scaled = |w: &[f64], att: f64, mw: f64| -> Vec<f64> {
        (0..n).map(|row| w[row] * att / mw).collect::<Vec<f64>>()
    };
    let subtract = |a: &[f64], b: &[f64]| -> Vec<f64> {
        (0..n).map(|row| a[row] - b[row]).collect::<Vec<f64>>()
    };

    let inf_treat_pre = subtract(
        &eta_treat_pre,
        &scaled(&w_treat_pre, att_treat_pre, mw_treat_pre),
    );
    let inf_treat_post = subtract(
        &eta_treat_post,
        &scaled(&w_treat_post, att_treat_post, mw_treat_post),
    );
    let negate = |v: Vec<f64>, by: f64| v.into_iter().map(|x| -x / by).collect::<Vec<f64>>();
    let m1_post = negate(moment(&design, &w_treat_post), mw_treat_post);
    let m1_pre = negate(moment(&design, &w_treat_pre), mw_treat_pre);
    let inf_treat_or_post = project(&control_post.asymptotic_linear, &m1_post, n);
    let inf_treat_or_pre = project(&control_pre.asymptotic_linear, &m1_pre, n);

    let inf_cont_pre = subtract(
        &eta_cont_pre,
        &scaled(&w_cont_pre, att_cont_pre, mw_cont_pre),
    );
    let inf_cont_post = subtract(
        &eta_cont_post,
        &scaled(&w_cont_post, att_cont_post, mw_cont_post),
    );
    let centred = |w: &[f64], att: f64| -> Vec<f64> {
        (0..n)
            .map(|row| w[row] * (residual(row) - att))
            .collect::<Vec<f64>>()
    };
    let m2_pre = moment(&design, &centred(&w_cont_pre, att_cont_pre));
    let m2_post = moment(&design, &centred(&w_cont_post, att_cont_post));
    let m2 = (0..k)
        .map(|col| m2_post[col] / mw_cont_post - m2_pre[col] / mw_cont_pre)
        .collect::<Vec<f64>>();
    let inf_cont_ps = project(&ps_representation, &m2, n);
    let m3_post = negate(moment(&design, &w_cont_post), mw_cont_post);
    let m3_pre = negate(moment(&design, &w_cont_pre), mw_cont_pre);
    let inf_cont_or_post = project(&control_post.asymptotic_linear, &m3_post, n);
    let inf_cont_or_pre = project(&control_pre.asymptotic_linear, &m3_pre, n);

    let inf_eff1 = subtract(&eta_d_post, &scaled(&w_d, att_d_post, mw_d));
    let inf_eff2 = subtract(&eta_dt1_post, &scaled(&w_dt1, att_dt1_post, mw_dt1));
    let inf_eff3 = subtract(&eta_d_pre, &scaled(&w_d, att_d_pre, mw_d));
    let inf_eff4 = subtract(&eta_dt0_pre, &scaled(&w_dt0, att_dt0_pre, mw_dt0));

    let difference = |a: &[f64], b: &[f64], scale_a: f64, scale_b: f64| -> Vec<f64> {
        (0..n)
            .map(|row| a[row] / scale_a - b[row] / scale_b)
            .collect::<Vec<f64>>()
    };
    let mom_post = moment(&design, &difference(&w_d, &w_dt1, mw_d, mw_dt1));
    let mom_pre = moment(&design, &difference(&w_d, &w_dt0, mw_d, mw_dt0));
    let or_gap = |treated_reg: &WeightedRegression, control_reg: &WeightedRegression| -> Vec<f64> {
        (0..n * k)
            .map(|i| treated_reg.asymptotic_linear[i] - control_reg.asymptotic_linear[i])
            .collect::<Vec<f64>>()
    };
    let inf_or_post = project(&or_gap(&treated_post, &control_post), &mom_post, n);
    let inf_or_pre = project(&or_gap(&treated_pre, &control_pre), &mom_pre, n);

    let influence_function = (0..n)
        .map(|row| {
            let treat = inf_treat_post[row] - inf_treat_pre[row]
                + inf_treat_or_post[row]
                + inf_treat_or_pre[row];
            let cont = inf_cont_post[row] - inf_cont_pre[row]
                + inf_cont_ps[row]
                + inf_cont_or_post[row]
                + inf_cont_or_pre[row];
            let efficiency = (inf_eff1[row] - inf_eff2[row]) - (inf_eff3[row] - inf_eff4[row]);
            let regression = inf_or_post[row] - inf_or_pre[row];
            (treat - cont) + efficiency + regression
        })
        .collect::<Vec<f64>>();

    let se = standard_error_from_influence(&influence_function);
    let (ci_low, ci_high) = multiplier_bootstrap_ci(
        att,
        &influence_function,
        config.inference(),
        config.bootstrap(),
    );

    Ok(DrDidEstimate {
        att,
        se,
        ci_low,
        ci_high,
        treated_n: prepared.treated_n,
        control_n: prepared.control_n,
        total_weight: prepared.total_weight,
        influence_function,
    })
}
